// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use DIRECT_DATABASE_URL for migrations (port 5432, not pooled)
    // Falls back to DATABASE_URL if DIRECT_DATABASE_URL is not set
    url: process.env["DIRECT_DATABASE_URL"] || process.env["DATABASE_URL"] || "postgresql://placeholder:placeholder@localhost:5432/placeholder",
  },
});
